[server]
enableCORS = false
enableXsrfProtection = false
headless = true

[browser]
serverAddress = "torq-app-dbd36yhetgbc7epzhitxhd.streamlit.app"
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"